sudo: false

language: php

cache:
  directories:
  - $HOME/.composer/cache
  - vendor

matrix:
  fast_finish: true
  include:
  - php: 5.5
  - php: 5.6
    env:
    - EXECUTE_DEPLOYMENT=true
  - php: 7
  - php: 7.1
  allow_failures:
  - php: 5.5

before_install:
- composer self-update

install:
- travis_retry composer install --no-interaction
- composer info -i

script:
- php vendor/bin/phpcs --standard=.cs/cs_ruleset.xml --extensions=php src/
#- php vendor/bin/phpcs --standard=.cs/cs_ruleset.xml --extensions=php tests/Tests/
#- php vendor/behat/behat/bin/behat

after_success:
- if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then composer install --no-dev ; fi
- if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./scripts/travis_deploy.bash ; fi

notifications:
  email: false
